ground_robot:
  - msg_topic: "/ublox/fix"
    msg_type: "sensor_msgs/NavSatFix"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"

aerial_robot:
  - msg_topic: "/mavros/global_position/raw/fix"
    msg_type: "sensor_msgs/NavSatFix"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"

  - msg_topic: "/camera/image_color/compressed"
    msg_type: "sensor_msgs/CompressedImage"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"

base_station:
  - msg_topic: "/dummy"
    msg_type: "std_msgs/Header"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"
