jackal:
  topics:
    rgb: "/camera/image_color"
    thermal: "/boson/image_raw"
    ouster: "/ouster/lidar_packets"
    gps: "/ublox/fix"
    rtk: "/rtcm"
    mic: "/audio/audio"
    jeti: "/joy"

falcon:
  topics:
    rgb: "/camera/image_color"
    thermal: "/boson/image_raw"
    gps: "/mavros/global_position/global/raw/fix"
    rtk: "/mavros/rtcm/in"

