basestation:
  node-type: "base_station"
  IP-address: "10.10.10.10"
  using-radio: "cardinal-3"
  base-port: "1234"
  clients:
    - "dione"
    - "phobos"
    - "deimos"
    - "titania"

dione:
  node-type: "aerial_robot"
  IP-address: "10.10.10.106"
  using-radio: "dx4-5"
  base-port: "6234"
  clients:
    - "basestation"
    - "phobos"
    - "deimos"
    - "titania"

phobos:
  node-type: "ground_robot"
  IP-address: "10.10.10.111"
  using-radio: "deep-blue-3"
  base-port: "2234"
  clients:
    - "basestation"
    - "dione"
    - "deimos"
    - "titania"

deimos:
  node-type: "ground_robot"
  IP-address: "10.10.10.112"
  using-radio: "deep-blue-2"
  base-port: "3234"
  clients:
    - "basestation"
    - "phobos"
    - "dione"
    - "titania"

titania:
  node-type: "ground_robot"
  IP-address: "10.10.10.114"
  using-radio: "deep-blue-5"
  base-port: 5254
  clients:
    - "basestation"
    - "phobos"
    - "deimos"
    - "dione"

